__author__ = "Marat Dukhan"
__copyright__ = "Copyright 2014-2015, Georgia Institute of Technology"
__credits__ = ["Marat Dukhan"]
__license__ = "Simplified BSD"
__version_info__ = ('0', '3', '6')
__version__ = '.'.join(__version_info__)
__maintainer__ = "Marat Dukhan"
__email__ = "maratek@gmail.com"
__status__ = "Development"
